CREATE TABLE BOARDS(
B_NUMBER NUMBER(10) NOT NULL,
B_TITLE VARCHAR2(50) NOT NULL,
B_PW NUMBER(4) NOT NULL,
B_CONTENT VARCHAR2(100) NOT NULL,
B_AUTHOR VARCHAR2(20) NOT NULL,
B_DATE VARCHAR2(30) NOT NULL,
B_FILE1 VARCHAR2(200),                             
B_FILE2 VARCHAR2(200),
B_FILE3 VARCHAR2(200),                       
B_HIT NUMBER(10) NOT NULL,
B_NOTICE NUMBER(1) NOT NULL,
B_RECOMMEND1 NUMBER(10) NOT NULL, 
B_RECOMMEND2 NUMBER(10) NOT NULL,
B_RECOMMEND3 NUMBER(10) NOT NULL,
CONSTRAINT PK_BOARDS PRIMARY KEY(B_NUMBER)
);
