CREATE TABLE REPLYS(
R_NUMBER NUMBER(10) NOT NULL,
R_AUTHOR VARCHAR(20) NOT NULL,
R_PW NUMBER(4) NOT NULL,
R_CONTENT VARCHAR(100) NOT NULL, 
R_DATE VARCHAR(30) NOT NULL,
B_NUMBER NUMBER(10) NOT NULL,
CONSTRAINT PK_REPLY PRIMARY KEY(R_NUMBER),
CONSTRAINT FK_BOARD FOREIGN KEY(B_NUMBER) REFERENCES BOARDS(B_NUMBER)
);
