CREATE TABLE USERS(
 U_ID VARCHAR2(20) NOT NULL,
 U_PW VARCHAR2(20) NOT NULL,
 U_NAME VARCHAR2(20) NOT NULL,
 U_MOBILE VARCHAR2(20) NOT NULL,
 U_EMAIL VARCHAR2(50) NOT NULL,
 U_GRADE VARCHAR2(1) NOT NULL,
 U_ENTRY_DATE VARCHAR2(50) NOT NULL,
 U_MILEAGE NUMBER(5),
 U_GENDER VARCHAR2(2) NOT NULL,
 U_BIRTH_YEAR NUMBER(4) NOT NULL,
 U_BIRTH_MONDAY VARCHAR2(10) NOT NULL,
 CONSTRAINT PK_USRES PRIMARY KEY (U_ID)
 );

 